---

- hosts: localhost
  tasks:
    - name: print os family
      debug:
        msg: '{{ ansible_os_family }}'
    - name: show user
      debug:
        msg: "user: {{ ansible_user_id }}"

  gather_facts: True
  roles:
    - base
    - golang
    - vscode

