
- name: 'Add vscode apt signing key'
  apt_key:
    url: '{{ ms_key_url }}'
    state: present
  become: yes

- name: 'Add vscode apt repo'
  apt_repository:
    repo: '{{ vscode_deb_repo }}'
    state: present
  become: yes
  notify:
    - Remove vscode deb repo

- name: 'Install vscode'
  apt:
    name: code
    update_cache: yes
    state: latest
  become: yes
