---
- name: Remove chrome deb repo
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: absent
  become: yes

- name: Remove docker deb repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: absent
  become: yes

- name: Restart docker service
  service:
    name: docker
    state: restarted
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    state: present
    groups: docker
    append: yes
    create_home: no
  become: yes
